language: python
env:
  - TOXENV=py38
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  coveralls --verbose
